name: krishi_mitra
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.1.2
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.4
  go_router: ^16.2.1
  google_fonts: ^6.3.1
  hooks_riverpod: ^2.6.1
  image_picker: ^1.0.7
  intl: ^0.20.2
  jwt_decoder: ^2.0.1
  permission_handler: ^11.3.0
  pinput: ^5.0.2
  profanity_filter: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
